server:
  basePath: {{server_basePath}}
  port: 3000
  loggingLevel: {{server_loggingLevel}}
  auth:
    algorithms: {{server_auth_algs}}
    privateKey: {{server_auth_pk}}
    audience: {{server_auth_aud}}
    issuer: {{server_auth_iss}}
  cors:
    origin: {{server_cors_origin}}
    credentials: {{server_cors_credentials}}
    methods: {{server_cors_methods}}
    allowedHeaders: {{server_cors_headers}}

database:
  mongo:
    name: {{database_mongo_name}}
    uri: {{database_mongo_uri}}
  
emailServer:
  host: {{emailServer_host}}
  user: {{emailServer_user}}
  pass: {{emailServer_pass}}

telegramServer:
  bot:
    username: {{telegramServer_bot_username}}
    token: {{telegramServer_bot_token}}
    webhook: {{telegramServer_bot_webhook}}